-- Triggers
-- 1) Statement.
-- Table qui stocke le nombre total de nageurs.
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE P17_Statistiques (
        StatID NUMBER PRIMARY KEY,
        NbTotalNageurs NUMBER
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN  -- Ignore l'erreur si la table existe déjà
            RAISE;
        END IF;
END;
/

-- Procedure qui sera appelée par le trigger
CREATE OR REPLACE PROCEDURE P17_Proc_UpdateTotalNageurs
AS
    total_nageurs NUMBER;
BEGIN
    -- Calculer le nombre total de nageurs
    SELECT COUNT(*) INTO total_nageurs FROM P17_Nageurs;

    -- Mettre à jour ou insérer les statistiques
    BEGIN
        UPDATE P17_Statistiques
        SET NbTotalNageurs = total_nageurs
        WHERE StatID = 1;

        IF SQL%ROWCOUNT = 0 THEN
            INSERT INTO P17_Statistiques (StatID, NbTotalNageurs)
            VALUES (1, total_nageurs);
        END IF;
    END;
END;
/

-- Création du trigger
CREATE OR REPLACE TRIGGER P17_Trigger_UpdateTotalNageurs
AFTER INSERT OR DELETE ON P17_Nageurs
BEGIN
    P17_Proc_UpdateTotalNageurs;
END;
/

-- Test du trigger 
-- Insertion multiple de nageurs
INSERT INTO P17_Nageurs (NageurID, NageurNom, NageurPrenom, NageurSexe, NageurPays, NageurDateNaissance)
VALUES
    (853, 'Dupont', 'Jean', 'H', 'FRA', DATE '2000-05-12'),
    (854, 'Martin', 'Sophie', 'F', 'USA', DATE '1998-03-22'),
    (855, 'Nguyen', 'Paul', 'H', 'VIE', DATE '2002-10-15');

-- Suppression d'un nageur
DELETE FROM P17_Nageurs
WHERE NageurNom = 'Dupont' AND NageurPrenom = 'Jean';

-- Vérification des statistiques
SELECT * FROM P17_Statistiques;

-- 2) ROW.
-- table qui sauvegarde l'historique des modifications.
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE P17_HistoriqueModifications (
        HistoriqueID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        OperationType VARCHAR2(10),
        NageurID NUMBER,
        EpreuveID NUMBER,
        DateModification TIMESTAMP,
        ValeursAnciennes CLOB,
        ValeursNouvelles CLOB
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN  -- Ignore l'erreur si la table existe déjà
            RAISE;
        END IF;
END;
/

-- Création de la procédure pour enregistrer les modifications
CREATE OR REPLACE PROCEDURE P17_Proc_LogModifications(
    operation_type IN VARCHAR2,
    old_values IN OUT CLOB,
    new_values IN OUT CLOB,
    nageur_id IN NUMBER,
    epreuve_id IN NUMBER
)
AS
BEGIN
    INSERT INTO P17_HistoriqueModifications (
        OperationType,
        NageurID,
        EpreuveID,
        DateModification,
        ValeursAnciennes,
        ValeursNouvelles
    )
    VALUES (
        operation_type,
        nageur_id,
        epreuve_id,
        SYSTIMESTAMP,
        old_values,
        new_values
    );
END;
/

-- Création du trigger
CREATE OR REPLACE TRIGGER P17_Trigger_LogModifications
AFTER INSERT OR UPDATE OR DELETE ON P17_ParticiperIndividuel
FOR EACH ROW
DECLARE
    old_values CLOB := NULL;
    new_values CLOB := NULL;
BEGIN
    -- Convertir les anciennes et nouvelles valeurs en JSON
    IF UPDATING OR DELETING THEN
        old_values := JSON_OBJECT(
            'NageurID' VALUE :OLD.NageurID,
            'EpreuveID' VALUE :OLD.EpreuveID,
            'Position' VALUE :OLD.Position,
            'Temps' VALUE :OLD.Temps,
            'Couloir' VALUE :OLD.Couloir,
            'Medaille' VALUE :OLD.Medaille
        );
    END IF;

    IF INSERTING OR UPDATING THEN
        new_values := JSON_OBJECT(
            'NageurID' VALUE :NEW.NageurID,
            'EpreuveID' VALUE :NEW.EpreuveID,
            'Position' VALUE :NEW.Position,
            'Temps' VALUE :NEW.Temps,
            'Couloir' VALUE :NEW.Couloir,
            'Medaille' VALUE :NEW.Medaille
        );
    END IF;

    -- Appel de la procédure pour enregistrer les modifications
    P17_Proc_LogModifications(
        operation_type => CASE
            WHEN INSERTING THEN 'INSERT'
            WHEN UPDATING THEN 'UPDATE'
            WHEN DELETING THEN 'DELETE'
        END,
        old_values => old_values,
        new_values => new_values,
        nageur_id => COALESCE(:OLD.NageurID, :NEW.NageurID),
        epreuve_id => COALESCE(:OLD.EpreuveID, :NEW.EpreuveID)
    );
END;
/

-- Test du trigger
-- Insertion d'une nouvelle participation
INSERT INTO P17_ParticiperIndividuel (NageurID, EpreuveID, Position, Temps, Couloir, Medaille)
VALUES (1, 101, 1, '00:50.11', 3, 'Or');

-- Mise à jour d'une participation existante
UPDATE P17_ParticiperIndividuel
SET Medaille = 'Argent'
WHERE NageurID = 1 AND EpreuveID = 101;

-- Suppression d'une participation
DELETE FROM P17_ParticiperIndividuel
WHERE NageurID = 1 AND EpreuveID = 101;

-- Vérification des modifications
SELECT * FROM P17_HistoriqueModifications;
